/**
 * Fallback content for the localStorage mock. It only has to be good enough to
 * keep the public site readable while the API is unreachable, so it is a
 * deliberately small subset of the real database rather than a mirror of it.
 */
export const SEEDS: Record<string, any[]> = {
  hero_slides: [
    {
      id: 1,
      src: "/assets/slider/mbp-img1.png",
      alt: "Milne Bay students and community learning",
      sort_order: 1,
      is_active: 1,
    },
    {
      id: 2,
      src: "/assets/slider/mbp-img2.png",
      alt: "Milne Bay Province schools and education",
      sort_order: 2,
      is_active: 1,
    },
    {
      id: 3,
      src: "/assets/slider/mbp-img3.png",
      alt: "Milne Bay coastal education community",
      sort_order: 3,
      is_active: 1,
    },
  ],
  news: [
    {
      id: 1,
      tag: "Announcement",
      tag_color: "bg-[#0D9488]",
      news_date: "September 18, 2026",
      title: "Grade 8 and Grade 10 Examination Timetable Released",
      excerpt:
        "The Division of Education has officially released the 2026 examination timetable for all Grade 8 and Grade 10 students across Milne Bay Province.",
      img: "https://images.unsplash.com/photo-1627423896085-e3e694d88e40?w=600&h=380&fit=crop&auto=format",
      is_published: 1,
      is_previous: 0,
    },
    {
      id: 2,
      tag: "Programs",
      tag_color: "bg-[#C9A84C] text-[#0B2545]",
      news_date: "September 10, 2026",
      title: "New VET Training Centres to Open in Alotau and Samarai",
      excerpt:
        "Two new Vocational Education and Training centres are set to open in Term 4, expanding skills-based learning opportunities for youth across the province.",
      img: "https://images.unsplash.com/photo-1632215861513-130b66fe97f4?w=600&h=380&fit=crop&auto=format",
      is_published: 1,
      is_previous: 0,
    },
    {
      id: 3,
      tag: "Notice",
      tag_color: "bg-[#0B2545]",
      news_date: "August 29, 2026",
      title: "School Subsidy Payment Schedule for Term 4 Now Available",
      excerpt:
        "Head teachers and school boards are advised to collect the Term 4 subsidy payment schedules from the Division office by 5 October 2026.",
      img: "https://images.unsplash.com/photo-1632932693914-89b90ae3d16d?w=600&h=380&fit=crop&auto=format",
      is_published: 1,
      is_previous: 0,
    },
  ],
  notices: [
    {
      id: 1,
      notice_date: "Sep 22",
      title: "PEB Meeting – October 2026 agenda published",
      is_published: 1,
    },
    {
      id: 2,
      notice_date: "Sep 17",
      title: "Teacher Relief Grant applications close 30 Sep",
      is_published: 1,
    },
    {
      id: 3,
      notice_date: "Sep 12",
      title: "Grade 12 trial exam results now available",
      is_published: 1,
    },
    {
      id: 4,
      notice_date: "Sep 5",
      title: "School board compliance audit schedule released",
      is_published: 1,
    },
    {
      id: 5,
      notice_date: "Aug 28",
      title: "Curriculum support materials distributed to all districts",
      is_published: 1,
    },
    {
      id: 6,
      notice_date: "Aug 20",
      title: "Annual School Sports Carnival registration open",
      is_published: 1,
    },
  ],
  events: [
    {
      id: 1,
      month: "OCT",
      day: "07",
      title: "Grade 8 National Examinations",
      event_time: "8:00 AM • All Centres",
      cat: "Examinations",
      color: "bg-[#0B2545]",
    },
    {
      id: 2,
      month: "OCT",
      day: "14",
      title: "PEB Quarterly Meeting in Alotau",
      event_time: "9:00 AM • Provincial HQ",
      cat: "Governance",
      color: "bg-[#0D9488]",
    },
    {
      id: 3,
      month: "NOV",
      day: "03",
      title: "School Sports Carnival 2026",
      event_time: "All Day • Alotau Oval",
      cat: "Co-Curricular",
      color: "bg-[#C9A84C] text-[#0B2545]",
    },
    {
      id: 4,
      month: "DEC",
      day: "05",
      title: "Grade 10 & 12 Results Release",
      event_time: "Online & School Noticeboards",
      cat: "Results",
      color: "bg-[#163663]",
    },
  ],
  programs: [
    {
      id: 1,
      code: "01",
      label: "Basic Education",
      level: "Elementary – Grade 8",
      description:
        "Providing foundational literacy, numeracy and life skills for all children from Prep through to Grade 8 across Milne Bay.",
      color: "bg-[#0B2545]",
      accent: "bg-teal-500",
      href: "/basic",
      img: "/assets/education_programs/basic/banner.png",
      sort_order: 1,
    },
    {
      id: 2,
      code: "02",
      label: "Post Primary",
      level: "Grade 9 – Grade 12",
      description:
        "Secondary education pathways preparing students for tertiary admission, technical training, and employment in the formal sector.",
      color: "bg-[#163663]",
      accent: "bg-amber-400",
      href: "/post",
      img: "/assets/education_programs/post/banner.png",
      sort_order: 2,
    },
    {
      id: 3,
      code: "03",
      label: "VET",
      level: "Vocational Education",
      description:
        "Skills and trades training for out-of-school youth and adults, delivered through registered VET providers across the province.",
      color: "bg-[#0D9488]",
      accent: "bg-amber-300",
      href: "/vet",
      img: "/assets/education_programs/vet/banner.png",
      sort_order: 3,
    },
    {
      id: 4,
      code: "04",
      label: "FODE",
      level: "Flexible Open & Distance",
      description:
        "Distance and open learning enabling students in remote areas to access quality secondary education without leaving their communities.",
      color: "bg-[#0B2545]",
      accent: "bg-teal-400",
      href: "/fode",
      img: "/assets/education_programs/fode/banner.png",
      sort_order: 4,
    },
  ],
  stats: [
    {
      id: 1,
      value_text: "312",
      label: "Schools",
      sub: "Province-wide",
      sort_order: 1,
    },
    {
      id: 2,
      value_text: "48,200+",
      label: "Students",
      sub: "Enrolled 2026",
      sort_order: 2,
    },
    {
      id: 3,
      value_text: "2,140",
      label: "Teachers",
      sub: "Qualified staff",
      sort_order: 3,
    },
    {
      id: 4,
      value_text: "17",
      label: "Districts",
      sub: "Covered",
      sort_order: 4,
    },
  ],
  districts: [
    { id: 1, name: "Alotau", schools: 42, type: "Urban", students: "6,800+" },
    {
      id: 2,
      name: "Samarai-Murua",
      schools: 22,
      type: "Island",
      students: "1,900+",
    },
    { id: 3, name: "Esa'ala", schools: 15, type: "Island", students: "1,600+" },
    {
      id: 4,
      name: "Kiriwina-Goodenough",
      schools: 18,
      type: "Island",
      students: "2,100+",
    },
    { id: 5, name: "Huhu", schools: 21, type: "Rural", students: "2,300+" },
    {
      id: 6,
      name: "Rabaruana",
      schools: 28,
      type: "Rural",
      students: "3,200+",
    },
    { id: 7, name: "Losuia", schools: 17, type: "Island", students: "1,700+" },
    { id: 8, name: "Dobu", schools: 16, type: "Island", students: "1,800+" },
  ],
  leadership: [
    {
      id: 1,
      name: "Dr. John K. Boro",
      title: "Provincial Education Advisor",
      bio: "Over 25 years in educational leadership across PNG. Holds a PhD in Educational Administration from UPNG.",
      icon: "👨‍💼",
      sort_order: 1,
    },
    {
      id: 2,
      name: "Ms. Margaret M. Tari",
      title: "Deputy Advisor - Basic Education",
      bio: "Former head teacher with extensive experience in elementary and primary curriculum implementation.",
      icon: "👩‍🏫",
      sort_order: 2,
    },
    {
      id: 3,
      name: "Mr. Peter G. Wai",
      title: "Deputy Advisor - Post Primary & VET",
      bio: "Specialist in secondary education pathways and vocational training coordination across the province.",
      icon: "👨‍🏫",
      sort_order: 3,
    },
    {
      id: 4,
      name: "Ms. Grace L. Kila",
      title: "Director - FODE & Distance Learning",
      bio: "Champion of flexible learning for remote communities. Masters in Distance Education from DWU.",
      icon: "👩‍💻",
      sort_order: 4,
    },
  ],
  quick_links: [
    {
      id: 1,
      icon: "calendar",
      label: "Term Dates",
      description: "2026 Academic Calendar",
      href: "/#news",
      sort_order: 1,
    },
    {
      id: 2,
      icon: "school",
      label: "School Directory",
      description: "Find schools in Milne Bay",
      href: "/basic#schools",
      sort_order: 2,
    },
    {
      id: 3,
      icon: "file",
      label: "Forms & Downloads",
      description: "Official documents",
      href: "/basic",
      sort_order: 3,
    },
    {
      id: 4,
      icon: "phone",
      label: "Emergency Contacts",
      description: "Helpline & support",
      href: "/contact",
      sort_order: 4,
    },
  ],
  partners: [
    { id: 1, name: "National Dept. of Education", sort_order: 1 },
    { id: 2, name: "Teaching Service Commission", sort_order: 2 },
    { id: 3, name: "TVET Authority", sort_order: 3 },
    { id: 4, name: "UNICEF PNG", sort_order: 4 },
    { id: 5, name: "Australia PNG Partnership", sort_order: 5 },
    { id: 6, name: "World Bank", sort_order: 6 },
  ],
  selections_grade9: [
    {
      id: 1,
      school: "Cameron Secondary School",
      district: "Alotau",
      type: "National High",
      capacity: 300,
      placed: 298,
      stream: "Science, Humanities, Business",
      cutoff: 185,
    },
    {
      id: 2,
      school: "Alotau Secondary School",
      district: "Alotau",
      type: "Provincial High",
      capacity: 250,
      placed: 248,
      stream: "Science, Humanities, Business, Technical",
      cutoff: 165,
    },
    {
      id: 3,
      school: "Bwesiruru Secondary",
      district: "Alotau",
      type: "Provincial High",
      capacity: 180,
      placed: 178,
      stream: "Science, Humanities, Business",
      cutoff: 145,
    },
    {
      id: 4,
      school: "Hagita Secondary School",
      district: "Alotau",
      type: "Provincial High",
      capacity: 160,
      placed: 158,
      stream: "Humanities, Business, Technical",
      cutoff: 135,
    },
    {
      id: 5,
      school: "Kiriwina Secondary School",
      district: "Kiriwina-Goodenough",
      type: "Provincial High",
      capacity: 120,
      placed: 118,
      stream: "Humanities, Business",
      cutoff: 125,
    },
  ],
  selections_grade11: [
    {
      id: 1,
      school: "Cameron Secondary School",
      district: "Alotau",
      type: "National High",
      streams_json: '{"Science":80,"Humanities":60,"Business":40}',
      placed_json: '{"Science":78,"Humanities":58,"Business":38}',
      cutoff_json: '{"Science":220,"Humanities":200,"Business":190}',
    },
    {
      id: 2,
      school: "Alotau Secondary School",
      district: "Alotau",
      type: "Provincial High",
      streams_json: '{"Science":60,"Humanities":50,"Business":40,"Technical":30}',
      placed_json: '{"Science":58,"Humanities":48,"Business":38,"Technical":28}',
      cutoff_json: '{"Science":200,"Humanities":185,"Business":175,"Technical":165}',
    },
  ],
  downloads: [
    {
      id: 1,
      name: "Basic Education Handbook 2026",
      type: "PDF",
      size_text: "2.4 MB",
      category: "Policy",
      description: "Complete handbook",
      file_path: "",
    },
  ],
  contact_messages: [],
  site_settings: [],
};
