// Regenerates the SEEDS block in src/lib/api.ts from the local MySQL database.
//
// A static Vercel deploy has no API to read from, so the frontend falls back to
// the hardcoded SEEDS. After editing content in the admin panel, run this so the
// deploy carries the current content instead of whatever was last committed here.
//
//   npm run export:seeds
//
// Rewrites only the region between the SEEDS markers. Everything else in the
// file - the api object, the fallback logic - is left untouched.

import mysql from "mysql2/promise";
import dotenv from "dotenv";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

dotenv.config();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
// The seed set lives in src/lib/seedData.ts, not api.ts: the refactor moved it
// out so the client module stays about the API.
const TARGET = path.join(__dirname, "..", "src", "lib", "seedData.ts");

// publicRead in server/index.js: entities a visitor may read without a token.
// selection_students and contact_messages hold personal data and stay out.
const ENTITIES = [
  "hero_slides",
  "news",
  "notices",
  "events",
  "programs",
  "stats",
  "districts",
  "schools",
  "leadership",
  "partners",
  "quick_links",
  "downloads",
  "selections_grade9",
  "selections_grade11",
  // Basic Education page sections, so a static deploy still shows them.
  "basic_hero",
  "basic_overview",
  "basic_overview_cards",
  "basic_overview_features",
  "basic_overview_stats",
  "basic_curriculum",
  "basic_initiatives",
  "basic_support",
  "basic_support_contact",
  "basic_faq",
  "basic_section_headings",
  // Post Primary page sections. selection_students is deliberately absent: it
  // holds minors' names and must never reach a client bundle.
  "post_hero",
  "post_overview",
  "post_overview_cards",
  "post_overview_features",
  "post_overview_stats",
  "post_streams",
  "post_assessment",
  "post_pathways",
  "post_initiatives",
  "post_support",
  "post_support_contact",
  "post_faq",
  "post_section_headings",
  // VET page sections. selection_students stays out: trainees' names.
  "vet_hero",
  "vet_overview",
  "vet_overview_cards",
  "vet_overview_features",
  "vet_overview_stats",
  "vet_programs",
  "vet_centres",
  "vet_centre_names",
  "vet_partners",
  "vet_apprenticeship",
  "vet_initiatives",
  "vet_enrolment_steps",
  "vet_intake_dates",
  "vet_support",
  "vet_support_contact",
  "vet_faq",
  "vet_section_headings",
  // FODE page sections. selection_students stays out: students' names.
  "fode_hero",
  "fode_overview",
  "fode_overview_cards",
  "fode_overview_features",
  "fode_overview_stats",
  "fode_programs",
  "fode_centres",
  "fode_delivery_methods",
  "fode_app_callout",
  "fode_enrolment_steps",
  "fode_key_dates",
  "fode_support",
  "fode_support_contact",
  "fode_initiatives",
  "fode_faq",
  "fode_section_headings",
  // Home page sections.
  "home_mission",
  "home_mission_points",
  "home_selection_banner",
  "home_cta",
  "home_cta_channels",
];

const START = "// AUTO-GENERATED BY scripts/export-seeds.mjs - do not edit by hand";
const END = "// END AUTO-GENERATED SEEDS";
const SEEDS_DECL = "export const SEEDS: Record<string, any[]> =";

function replaceBlock(source, block) {
  const anchor = source.indexOf(SEEDS_DECL);
  if (anchor === -1) return null;
  // Keep the existing doc comment above the declaration, and everything after
  // the object literal.
  const open = source.indexOf("{", anchor);
  let depth = 0;
  let i = open;
  let inStr = null;
  let inTpl = false;
  for (; i < source.length; i++) {
    const c = source[i];
    if (inStr) {
      if (c === "\\") i++;
      else if (c === inStr) inStr = null;
      continue;
    }
    if (inTpl) {
      if (c === "\\") i++;
      else if (c === "`") inTpl = false;
      continue;
    }
    if (c === '"' || c === "'") { inStr = c; continue; }
    if (c === "`") { inTpl = true; continue; }
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) return { head: source.slice(0, open), tail: source.slice(i + 1) };
    }
  }
  return null;
}

const DB = {
  host: process.env.DB_HOST || "127.0.0.1",
  port: Number(process.env.DB_PORT || 3306),
  user: process.env.DB_USER || "root",
  password: process.env.DB_PASSWORD || "",
  database: process.env.DB_NAME || "mbp_education",
};

const pool = mysql.createPool(DB);

// An upload that recorded an absolute dev URL (http://localhost:3001/...) 404s
// on any other host, because the browser resolves localhost to the visitor's
// own machine. The upload route already returns relative paths, but rows saved
// before that returned full URLs are still in the database.
function relativise(value) {
  if (typeof value !== "string") return value;
  return value.replace(/https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?\//g, "/");
}

// Some rows hold inline base64 images ("data:image/png;base64,...") pasted in
// rather than uploaded as files. A handful of those is several megabytes, which
// blows the browser's ~5 MB localStorage quota once every entity is seeded, and
// inlining them also bloats the JS bundle for every visitor. They are dropped
// so the row still renders, with a placeholder src.
const DROPPED = {};
function stripDataUrls(value, key) {
  if (typeof value !== "string" || !value.startsWith("data:")) return value;
  DROPPED[key] = (DROPPED[key] || 0) + 1;
  return "";
}

function normalise(value, column = "") {
  if (Array.isArray(value)) return value.map((v) => normalise(v, column));
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([k, v]) => [k, normalise(v, k)]),
    );
  }
  if (typeof value === "string" && value.startsWith("data:")) {
    return stripDataUrls(value, column);
  }
  return relativise(value);
}

const source = fs.readFileSync(TARGET, "utf8");
const parts = replaceBlock(source);
if (!parts) {
  console.error(`Could not find the SEEDS object literal in ${TARGET}.`);
  process.exit(1);
}

const block = {};
try {
  for (const entity of ENTITIES) {
    const [rows] = await pool.query(
      `SELECT * FROM \`${entity}\` ORDER BY id ASC`,
    );
    block[entity] = rows.map((r) => normalise(r));
  }
} finally {
  await pool.end();
}

// replaceBlock returns the text up to the object's opening brace (which
// includes the declaration's "=") and everything after the closing brace, so
// only the body is rejoined here. JSON.stringify emits its own braces, so the
// inner text is indented and wrapped rather than pasted whole.
const inner = JSON.stringify(block, null, 2).slice(1, -1).replace(/^/gm, "  ");
const next =
  parts.head +
  "{\n  // AUTO-GENERATED by scripts/export-seeds.mjs - do not edit by hand.\n" +
  "  // Regenerate with: npm run export:seeds\n" +
  inner +
  "\n}" +
  parts.tail;
const sizeKb = (Buffer.byteLength(JSON.stringify(block), "utf8") / 1024).toFixed(0);
if (Object.keys(DROPPED).length) {
  const detail = Object.entries(DROPPED)
    .map(([col, n]) => `${col} (${n} row${n > 1 ? "s" : ""})`)
    .join(", ");
  console.log(
    `Dropped inline base64 images from: ${detail}.\n` +
      `Those columns are cleared in the seeds only - the database is untouched.\n` +
      `Upload them as files via the admin panel so they get a real /uploads path.`,
  );
}
console.log(`Seed payload: ${sizeKb} KB (browser localStorage allows about 5120 KB)`);
if (next === source) {
  console.log("Seeds already up to date - no changes written.");
} else {
  fs.writeFileSync(TARGET, next, "utf8");
  const summary = Object.entries(block)
    .map(([k, v]) => `${k}=${v.length}`)
    .join(" ");
  console.log(`Seeds regenerated in src/lib/api.ts\n  ${summary}`);
}
