// Regenerates the SEEDS block in src/lib/api.ts from the local MySQL database.
//
// A static Vercel deploy has no API to read from, so the frontend falls back to
// the hardcoded SEEDS. After editing content in the admin panel, run this so the
// deploy carries the current content instead of whatever was last committed here.
//
//   npm run export:seeds
//
// Rewrites only the region between the SEEDS markers. Everything else in the
// file - the api object, the fallback logic - is left untouched.

import mysql from "mysql2/promise";
import dotenv from "dotenv";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

dotenv.config();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TARGET = path.join(__dirname, "..", "src", "lib", "api.ts");

// publicRead in server/index.js: entities a visitor may read without a token.
// selection_students and contact_messages hold personal data and stay out.
const ENTITIES = [
  "hero_slides",
  "news",
  "notices",
  "events",
  "programs",
  "stats",
  "districts",
  "schools",
  "leadership",
  "partners",
  "quick_links",
  "downloads",
  "selections_grade9",
  "selections_grade11",
  // Basic Education page sections, so a static deploy still shows them.
  "basic_hero",
  "basic_overview",
  "basic_overview_cards",
  "basic_overview_features",
  "basic_overview_stats",
  "basic_curriculum",
  "basic_initiatives",
  "basic_support",
  "basic_support_contact",
  "basic_faq",
  "basic_section_headings",
];

const START = "// AUTO-GENERATED BY scripts/export-seeds.mjs - do not edit by hand";
const END = "// END AUTO-GENERATED SEEDS";

const DB = {
  host: process.env.DB_HOST || "127.0.0.1",
  port: Number(process.env.DB_PORT || 3306),
  user: process.env.DB_USER || "root",
  password: process.env.DB_PASSWORD || "",
  database: process.env.DB_NAME || "mbp_education",
};

const pool = mysql.createPool(DB);

// An upload that recorded an absolute dev URL (http://localhost:3001/...) 404s
// on any other host, because the browser resolves localhost to the visitor's
// own machine. The upload route already returns relative paths, but rows saved
// before that returned full URLs are still in the database.
function relativise(value) {
  if (typeof value !== "string") return value;
  return value.replace(/https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?\//g, "/");
}

function normalise(value) {
  if (Array.isArray(value)) return value.map(normalise);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([k, v]) => [k, normalise(v)]),
    );
  }
  return relativise(value);
}

const source = fs.readFileSync(TARGET, "utf8");
const start = source.indexOf(START);
const end = source.indexOf(END);
if (start === -1 || end === -1) {
  console.error("Could not find the generated-seeds markers in src/lib/api.ts.");
  process.exit(1);
}

const block = {};
try {
  for (const entity of ENTITIES) {
    const [rows] = await pool.query(
      `SELECT * FROM \`${entity}\` ORDER BY id ASC`,
    );
    block[entity] = rows.map(normalise);
  }
} finally {
  await pool.end();
}

const body = `${START}
const SEEDS: Record<string, any[]> = ${JSON.stringify(block, null, 2)};

${END}`;

const next = source.slice(0, start) + body + source.slice(end + END.length);
if (next === source) {
  console.log("Seeds already up to date - no changes written.");
} else {
  fs.writeFileSync(TARGET, next, "utf8");
  const summary = Object.entries(block)
    .map(([k, v]) => `${k}=${v.length}`)
    .join(" ");
  console.log(`Seeds regenerated in src/lib/api.ts\n  ${summary}`);
}
